### ISSUE TITLE
Test of exponential sensitivity

### ISSUE THREAD

**Issue by zunzun** [vicrucann/CurveFitting#1]
This is James Phillips, author of the Python language pyeq3 curve fitting library on GitHub at https://github.com/zunzun/pyeq3.  I include in my code's unit tests a test of exponential sensitivity that you might be interested in, the equation to be fitted is

y = a * exp(bx) + Offset

and the data for the test is

 x                  y
0.9         -2997.81165143259
1.5         -2997.67633151454
13.8         -2992.05019674501
19.8         -2985.51451402968
24.1         -2977.73207770987
28.2         -2966.44629865572
35.2          -2932.4311430723
60.3         -2168.56994123603
74.6          474.296114697706
81.3          3789.59913028271

Fitted coefficients should be

a = 2.0
b = 0.1
Offset = -3000.0

The test is quite sensitive.  My nonlinear fitter uses the Differential Evolution genetic algorithm to determine initial parameters for the Levenberg-Marquardt nonlinear fitter in scipy's Python fitter.

James

**Comment by vicrucann** [comment]
Hi James,

Thanks for the suggested test, I might try it later!
